### ISSUE TITLE
Famous same problem but twrp (3.3.1-0-cheeseburger.img) not able to decrpt the phone data.

### ISSUE THREAD

**Issue by PranavBhattarai** [TeamWin/android_device_oneplus_cheeseburger_dumpling#9]
What should I do in this case?

Device: Oneplus 5
Twrp downloaded from: https://dl.twrp.me/cheeseburger/
Problem: Twrp recovery not recognizing the phone's password.

**Comment by mauronofrio** [comment]
Solved the problem with the latest build @nitramwin @meganukebmp @PranavBhattarai
